name: CI

on:
  push:
    branches:
    - main
    - "run-ci/**"
    - "**/run-ci/**"
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      run: |
        rustup update stable
        rustup default stable
        rustup component add clippy rustfmt
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy
    - name: tests
      run: make tests
    - name: "Test (crossterm)"
      run: |
        cargo test --features=render-tui,render-tui-crossterm,render-line,render-line-crossterm,signal-hook,render-line-autoconfigure,progress-tree --all --bins --tests --examples
    - name: benchmarks
      run: make bench-ci

  build-and-test-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Rust
      shell: bash  # Use `bash` even on Windows, for `set -e` behavior.
      run: |
        rustup update stable
        rustup default stable
    - name: "Check (crossterm)"
      run: |
        cargo check --features=render-tui,render-tui-crossterm,render-line,render-line-crossterm,signal-hook,render-line-autoconfigure,progress-tree --all --bins --tests --examples
    - name: "Test (crossterm)"
      run: |
        cargo test --features=render-tui,render-tui-crossterm,render-line,render-line-crossterm,signal-hook,render-line-autoconfigure,progress-tree --all -- --skip render::tui
